"""Phase 5 - per-prediction attribution and the LLM explanation layer.

The boundary, stated once and enforced in code:

    The classifier decides. The LLM writes.

The language model never sees the label, never sees the threshold, and its
output never re-enters the decision path. It is handed a frozen, structured
payload - the order's facts plus the top TreeSHAP contributions already
converted into evidence sentences - and asked to render that payload as prose a
human reviewer can act on. If the API key is absent, a deterministic template
writer produces the same content without the prose polish, so the repo runs on a
clean machine with no key and no network.

That ordering matters for a second reason: an explanation generated from the
attributions is auditable against them. An explanation generated by asking a
model "is this fraud?" would be a second, uncalibrated classifier wearing a
justification costume.
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from features import FEATURE_COLUMNS  # noqa: E402

MODEL_ID = "claude-sonnet-4-5"

# feature -> (direction-aware sentence template, formatter)
EVIDENCE = {
    "comp_size":
        lambda v: "the account sits in an identity cluster of %d linked accounts" % v,
    "comp_growth_d7":
        lambda v: "%.1f new account-to-account links formed in that cluster in the past week"
        % v,
    "comp_orders_d7":
        lambda v: "the cluster placed the equivalent of %.1f orders in the past week" % v,
    "comp_orders_d30":
        lambda v: "the cluster placed the equivalent of %.1f orders in the past month" % v,
    "comp_mean_tenure_days":
        lambda v: "the average account in the cluster is %d days old" % v,
    "comp_max_tenure_days":
        lambda v: "the oldest account in the cluster is %d days old" % v,
    "comp_return_rate":
        lambda v: "the cluster's settled return rate is %.0f%%" % (100 * v),
    "comp_cod_share":
        lambda v: "%.0f%% of the cluster's prior orders were cash-on-delivery" % (100 * v),
    "comp_distinct_devices":
        lambda v: "the cluster has used %d distinct devices" % v,
    "comp_distinct_addr_clusters":
        lambda v: "the cluster has shipped to %d distinct addresses" % v,
    "comp_value_per_customer":
        lambda v: "cluster spend averages Rs %.0f per account" % v,
    "comp_orders_per_customer":
        lambda v: "cluster activity averages %.1f orders per account" % v,
    "comp_prior_orders":
        lambda v: "the cluster has %d prior orders on record" % v,
    "cust_tenure_days":
        lambda v: "the account is %d days old" % v,
    "cust_prior_orders":
        lambda v: "the account has %d prior orders" % v,
    "cust_return_rate":
        lambda v: "the account's smoothed return rate is %.0f%%" % (100 * v),
    "cust_prior_returns":
        lambda v: "the account has %d settled returns" % v,
    "cust_cod_share":
        lambda v: "%.0f%% of the account's prior orders were cash-on-delivery" % (100 * v),
    "cust_orders_d7":
        lambda v: "the account placed the equivalent of %.1f orders in the past week" % v,
    "cust_orders_d30":
        lambda v: "the account placed the equivalent of %.1f orders in the past month" % v,
    "cust_value_z":
        lambda v: "this cart is %.1f standard deviations from the account's usual order value"
        % v,
    "cust_days_since_last":
        lambda v: ("this is the account's first order" if v > 900
                   else "the previous order was %.1f days ago" % v),
    "cust_mean_value":
        lambda v: "the account's prior orders average Rs %.0f" % v,
    "cust_max_value":
        lambda v: "the account's largest prior order was Rs %.0f" % v,
    "cust_distinct_devices":
        lambda v: "the account has used %d devices" % v,
    "cust_distinct_addr_clusters":
        lambda v: "the account has shipped to %d distinct addresses" % v,
    "dev_distinct_customers":
        lambda v: "this device has been used by %d other accounts" % v,
    "dev_prior_orders":
        lambda v: "this device has %d prior orders" % v,
    "dev_return_rate":
        lambda v: "this device's settled return rate is %.0f%%" % (100 * v),
    "dev_age_days":
        lambda v: "this device was first seen %d days ago" % v,
    "addr_distinct_customers":
        lambda v: "%d other accounts have shipped to this address" % v,
    "addr_variant_count":
        lambda v: "this address has been written %d different ways" % v,
    "addr_is_new_variant_of_known_cluster":
        lambda v: ("the shipping address is a new spelling of an address already delivered to"
                   if v >= 0.5 else "the shipping address is spelled as previously seen"),
    "addr_prior_orders":
        lambda v: "this address has received %d prior orders" % v,
    "addr_return_rate":
        lambda v: "this address's settled return rate is %.0f%%" % (100 * v),
    "phone_neighbours_active":
        lambda v: "%d active accounts use phone numbers numerically adjacent to this one" % v,
    "phone_neighbour_orders":
        lambda v: "numerically adjacent phone numbers account for %d prior orders" % v,
    "pin_distinct_customers":
        lambda v: "%d accounts are active in this pincode" % v,
    "pin_prior_orders": lambda v: "this pincode has %d prior orders" % v,
    "pin_return_rate":
        lambda v: "this pincode's settled return rate is %.0f%%" % (100 * v),
    "value_inr": lambda v: "the cart is Rs %.0f" % v,
    "log_value": lambda v: "the cart is Rs %.0f" % (np.expm1(v)),
    "value_over_cat_mean":
        lambda v: "the cart is %.1fx the running average for its category" % v,
    "cat_return_rate_prior":
        lambda v: "this category's marketplace return rate is %.0f%%" % (100 * v),
    # scale-free rates
    "cust_orders_per_day":
        lambda v: "the account has ordered %.2f times per day since signup" % v,
    "dev_orders_per_day":
        lambda v: "this device has ordered %.2f times per day since first seen" % v,
    "addr_orders_per_day":
        lambda v: "this address has received %.2f orders per day since first seen" % v,
    "comp_orders_per_member_per_day":
        lambda v: "the cluster averages %.3f orders per account per day" % v,
    "addr_age_days":
        lambda v: "this address was first shipped to %d days ago" % v,
    "pin_orders_share":
        lambda v: "this pincode is %.2f%% of all marketplace orders so far" % (100 * v),
    "pin_cust_share":
        lambda v: "this pincode holds %.2f%% of all known customers" % (100 * v),
    "comp_orders_share":
        lambda v: "this cluster is %.3f%% of all marketplace orders so far" % (100 * v),
    "item_count": lambda v: "the cart has %d items" % v,
    "promo_used": lambda v: ("a promotion was applied" if v >= 0.5 else "no promotion applied"),
    "hour_of_day": lambda v: "the order was placed at %02d:00" % v,
    "is_night": lambda v: ("the order was placed overnight" if v >= 0.5
                           else "the order was placed during the day"),
    "day_of_week": lambda v: "placed on day %d of the week" % v,
}
for _c in ["apparel", "footwear", "electronics", "beauty", "grocery"]:
    EVIDENCE["cat_" + _c] = (lambda name: lambda v: "the cart is in %s" % name)(_c)


class Attributor:
    """TreeSHAP over the uncalibrated booster.

    Attribution is taken on the booster's margin, not on the calibrated
    probability: isotonic regression is a monotone post-hoc map, so it changes
    the number but not the ordering or the reasons. Attributing through it would
    add a step with no interpretable per-feature meaning.
    """

    def __init__(self, bundle):
        import shap
        self.clf = bundle["booster"]
        self.features = bundle["features"]
        self.explainer = shap.TreeExplainer(self.clf.booster_)

    def shap_values(self, X):
        sv = self.explainer.shap_values(X)
        if isinstance(sv, list):
            sv = sv[1] if len(sv) > 1 else sv[0]
        sv = np.asarray(sv)
        if sv.ndim == 3:
            sv = sv[:, :, 1] if sv.shape[2] > 1 else sv[:, :, 0]
        return sv

    def top_evidence(self, x_row, sv_row, k=5, direction="up"):
        idx = np.argsort(-sv_row if direction == "up" else sv_row)[:k]
        out = []
        for j in idx:
            name = self.features[j]
            contrib = float(sv_row[j])
            if direction == "up" and contrib <= 0:
                continue
            if direction == "down" and contrib >= 0:
                continue
            val = float(x_row[j])
            fn = EVIDENCE.get(name)
            out.append(dict(feature=name, value=val, contribution=contrib,
                            sentence=fn(val) if fn else "%s = %.3f" % (name, val)))
        return out


def caveats(order_facts, feat_map):
    """What this flag does NOT establish. Written from the same feature row.

    The brief asks for an honest list of what the system could not resolve. This
    is that list, per order, and it is generated from rules over the features
    rather than by asking the model to be humble.
    """
    out = []
    g = feat_map.get
    if g("cust_prior_orders", 0) == 0:
        out.append("This account has no order history, so every behavioural signal is absent; "
                   "the score rests entirely on network structure.")
    if g("addr_distinct_customers", 0) >= 1 and g("comp_max_tenure_days", 0) > 365:
        out.append("At least one account in this cluster is over a year old. Order data alone "
                   "cannot separate a co-ordinated group from a genuine shared household.")
    if g("addr_is_new_variant_of_known_cluster", 0) >= 0.5:
        out.append("The address matched an existing cluster by text normalisation, not by "
                   "geocoding. A normalisation error would produce this same signal.")
    if g("comp_size", 1) <= 1:
        out.append("No identity links were found at all; this flag is behavioural only and is "
                   "the weakest kind of evidence this system produces.")
    if g("phone_neighbours_active", 0) > 0:
        out.append("Numerically adjacent phone numbers can also arise from a family or a small "
                   "business buying a connection block legitimately.")
    if not out:
        out.append("No specific counter-hypothesis was detected, which is not the same as none "
                   "existing.")
    return out


SYSTEM_PROMPT = """You are a risk-operations assistant for an e-commerce merchant's \
returns-abuse review queue. You write short justifications that a human reviewer reads \
before deciding whether to require prepayment on a cash-on-delivery order.

Hard rules:
- You are NOT the classifier. A calibrated model has already scored this order. Never \
agree or disagree with the score, never restate it as your own judgement, and never \
suggest a different score.
- Use ONLY the evidence supplied. Never introduce a fact that is not in the payload. \
Never speculate about the customer's identity, intent, motive or character.
- Write for the merchant's defensive side only. Never describe how detection could be \
avoided.
- Include the supplied caveats faithfully. They are the point, not a disclaimer.

Output 3 to 4 sentences of plain prose. First what the evidence shows, then what it does \
not establish. No bullet points, no headings, no preamble."""


def _dedupe(seq):
    """Several features can render to the same sentence (a one-member cluster has
    the same age as its only account). Say it once."""
    seen, out = set(), []
    for x in seq:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out


def _template_explanation(payload):
    sents = _dedupe([e["sentence"] for e in payload["evidence"]])
    ev = "; ".join(sents)
    top = sents[0] if sents else "no positive evidence"
    return ("Flagged for review at a calibrated abuse probability of %.3f. The strongest "
            "single factor is that %s. Supporting signals: %s. What this does not establish: %s"
            % (payload["probability"], top, ev, " ".join(payload["caveats"])))


def write_explanation(payload, use_llm=True, client=None):
    """Render one explanation. Falls back to a deterministic template with no key."""
    if not use_llm or not os.environ.get("ANTHROPIC_API_KEY"):
        return _template_explanation(payload), "template"
    try:
        if client is None:
            import anthropic
            client = anthropic.Anthropic()
        msg = client.messages.create(
            model=MODEL_ID, max_tokens=400, system=SYSTEM_PROMPT,
            messages=[{"role": "user",
                       "content": "Evidence payload (JSON):\n" + json.dumps(payload, indent=2)}])
        return msg.content[0].text.strip(), MODEL_ID
    except Exception as e:  # network, auth, rate limit - never break the pipeline
        return _template_explanation(payload), "template (LLM unavailable: %s)" % type(e).__name__


def build_payload(order_facts, x_row, sv_row, attributor, probability, band, k=5):
    feat_map = {attributor.features[j]: float(x_row[j]) for j in range(len(x_row))}
    up = attributor.top_evidence(x_row, sv_row, k=k, direction="up")
    down = attributor.top_evidence(x_row, sv_row, k=2, direction="down")
    return dict(
        order=order_facts,
        probability=float(probability),
        decision_band=band,
        evidence=up,
        counter_evidence=down,
        caveats=caveats(order_facts, feat_map),
    )
